apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daytrader-portfolios
  name: daytrader-portfolios
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daytrader-portfolios
  template:
    metadata:
      labels:
        app: daytrader-portfolios
    spec:
      containers:
      - name: daytrader-portfolios
        image: vayalankatil/daytrader-portfolios:4.0.19
        imagePullPolicy: Always
        ports:
        - containerPort: 3443
          protocol: TCP
        readinessProbe:  
          httpGet:
            path: /health
            scheme: HTTPS
            port: 3443
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
        livenessProbe:  
          httpGet:
            path: /health
            scheme: HTTPS
            port: 3443
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 4
        env:
        - name: ACCOUNTS_SERVICE_ROUTE
          value: https://daytrader-accounts
        - name: GATEWAY_SERVICE_ROUTE
          value: https://daytrader-gateway
        - name: PORTFOLIOS_SERVICE_ROUTE
          value: https://daytrader-portfolios
        - name: QUOTES_SERVICE_ROUTE
          value: https://daytrader-quotes
        - name: DAYTRADER_DATABASE_DRIVER
          value: com.mysql.jdbc.Driver
        - name: DAYTRADER_DATABASE_PASSWORD
          value: dummy
        - name: DAYTRADER_DATABASE_URL
          value: jdbc:mysql://mysqlportfolios/portfolios?autoReconnect=true&useSSL=false
        - name: DAYTRADER_DATABASE_USERNAME
          value: sudheesh
        - name: GET_HOSTS_FROM
          value: dns
